# permissions for end users to view cascadenodemanagers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cascadenodemanager-viewer-role
rules:
- apiGroups:
  - derecho.poanpan
  resources:
  - cascadenodemanagers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - derecho.poanpan
  resources:
  - cascadenodemanagers/status
  verbs:
  - get
