# permissions for end users to edit cascadenodemanagers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cascadenodemanager-editor-role
rules:
- apiGroups:
  - derecho.poanpan
  resources:
  - cascadenodemanagers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - derecho.poanpan
  resources:
  - cascadenodemanagers/status
  verbs:
  - get
